### ISSUE TITLE
Problem with extraction

### ISSUE THREAD

**Issue by Katkat95** [BlackDragonHunt/Reverse-Engineering#1]
Hello, I have a problem with running the script under Persona 5, I tried to extract the Eboot and I am left with an empty directory regarding the text files no file is generated. Do you have a solution? thank you
(NPEB02436)

**Comment by yukinogatari** [comment]
My guess on the first issue would be the EBOOT is still encrypted, so it's not finding anything to extract.

As for it not exporting any text, I need more information about what your work environment looks like to guess what might be going wrong. Have you extracted the game's data.cpk and ps3.cpk files? And did you modify the p5_text.py script to point to the folders where you extracted those CPKs on your own computer?
